### ISSUE TITLE
Restrict tree creation based off subscription plan

### ISSUE THREAD

**Issue by curtisdelicata** [familytree365/nuxt#23]
This is  a **bug | feature request**.

### Prerequisites
* [x] #190
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/familytree365)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

**Comment by curtisdelicata** [comment]
Tree creation to be tested and only allow new trees if subscription allows. One tree, ten tree and unlimited tree packages.

**Comment by jacob-liu-g** [comment]
@everyone you got scammed, please check @curtisdelicata 's Linkedin profile. He is fraud and liar. He never pay for developers.

He runs fake business called FamilyTree365. He lies developers to contribute the project for a week and pretend to pay after a week but he disappears after receiving PR.

I should alert other honest developers and customers that you should never support Curtis Delicata since he is a fraud.

I can share you more evidence if anybody interested.

https://www.linkedin.com/feed/update/urn:li:activity:6906662303572606976/
